### ISSUE TITLE
Hard-coded reslice parameters

### ISSUE THREAD

**Issue by ashgillman** [UCL/petmr-rd-tools#8]
Hi,

It seems that not all MRAC acqusitions are made in the same resolution and size, and so some parameters in MRAC.hpp may not generalise.

I see resliceDefaultParams are defined as a JSON array, perhaps this could be specified as input?

sx, sy and sz aren't used from the params, rather calculated. Maybe they should only be calculated if not supplied in the params?

The xy padding of 100 and z cropping of (11,10) also seem to be tied to a specific acquisition, however I'm not sure of the best way to calculate appropriate values. Perhaps these operations are not actually required?

Cheers,
Ash

**Comment by bathomas** [comment]
Hi @ashgillman,

You're quite right, the JSON array is ultimately intended as an (optional) input. I will implement this. 

I'm getting hold of different acquisitions and will try and come up with something.

Kind regards,

Ben

**Comment by ashgillman** [comment]
Great, I have a phantom acquisition I may be able to share offline. Let me know if it would help and I can talk to my supervisor about sharing.
